In [22]:
import numpy as np
x = np.array([1,2,3,4,5])
print("The array is : ",x)

The array is :  [1 2 3 4 5]


In [13]:
x = np.ones(10)
print("The array of 1s  is : ",x)

The array of 1s  is :  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [14]:
x = np.zeros(5)
print("The array of 0s is : ",x)

The array of 0s is :  [0. 0. 0. 0. 0.]


In [15]:
x = np.arange(1,10)
print(x)
x = np.arange(5,11)
print(x)
x = np.arange(1,10,2)   # arrange from 1 to 10 with 2 steps
print(x)

[1 2 3 4 5 6 7 8 9]
[ 5  6  7  8  9 10]
[1 3 5 7 9]


In [16]:
x = np.linspace(1,10)
print(x)
print( len(x) )   # total no of elements in x

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]
50


In [17]:
x = x**2    # taking square of all values of x
print(x)

[  1.           1.40108288   1.86963765   2.40566431   3.00916285
   3.68013328   4.41857559   5.2244898    6.09787589   7.03873386
   8.04706372   9.12286547  10.26613911  11.47688463  12.75510204
  14.10079134  15.51395252  16.99458559  18.54269055  20.15826739
  21.84131612  23.59183673  25.40982924  27.29529363  29.2482299
  31.26863807  33.35651812  35.51187005  37.73469388  40.02498959
  42.38275718  44.80799667  47.30070804  49.8608913   52.48854644
  55.18367347  57.94627239  60.77634319  63.67388588  66.63890046
  69.67138692  72.77134527  75.93877551  79.17367763  82.47605165
  85.84589754  89.28321533  92.788005    96.36026656 100.        ]


In [18]:
x = np.sqrt(x)    # taking sqraue root of the above squared x
print(x)   

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]


In [19]:
x1 = x+x   # adding the array x with itself
print(x1)

[ 2.          2.36734694  2.73469388  3.10204082  3.46938776  3.83673469
  4.20408163  4.57142857  4.93877551  5.30612245  5.67346939  6.04081633
  6.40816327  6.7755102   7.14285714  7.51020408  7.87755102  8.24489796
  8.6122449   8.97959184  9.34693878  9.71428571 10.08163265 10.44897959
 10.81632653 11.18367347 11.55102041 11.91836735 12.28571429 12.65306122
 13.02040816 13.3877551  13.75510204 14.12244898 14.48979592 14.85714286
 15.2244898  15.59183673 15.95918367 16.32653061 16.69387755 17.06122449
 17.42857143 17.79591837 18.16326531 18.53061224 18.89795918 19.26530612
 19.63265306 20.        ]


In [20]:
x2 = x*x
print(x2)

[  1.           1.40108288   1.86963765   2.40566431   3.00916285
   3.68013328   4.41857559   5.2244898    6.09787589   7.03873386
   8.04706372   9.12286547  10.26613911  11.47688463  12.75510204
  14.10079134  15.51395252  16.99458559  18.54269055  20.15826739
  21.84131612  23.59183673  25.40982924  27.29529363  29.2482299
  31.26863807  33.35651812  35.51187005  37.73469388  40.02498959
  42.38275718  44.80799667  47.30070804  49.8608913   52.48854644
  55.18367347  57.94627239  60.77634319  63.67388588  66.63890046
  69.67138692  72.77134527  75.93877551  79.17367763  82.47605165
  85.84589754  89.28321533  92.788005    96.36026656 100.        ]


In [21]:
x3 = x/x
print(x3)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1.]
